### ISSUE TITLE
vimeo interactivity tools

### ISSUE THREAD

**Issue by christianck02031995** [javdome/vimeo-interactive#1]
Hi all,

Is there is any api reference to add an interactivity tool in the uploaded video - Vimeo
Can anyone suggest a method to add interactivity tool in Vimeo video

**Comment by javdome** [comment]
Hi!!
At the moment there is no api reference... what kind of interactivity so you want to add??

**Comment by christianck02031995** [comment]
Hi,
In between video performing some action or events.
for example showing a question and its options like that.

**Comment by javdome** [comment]
Now is available the "Modal with choosing options":
![Modal](https://user-images.githubusercontent.com/36993404/80379106-ef0bea80-889d-11ea-9f9e-438ac2142148.jpg)

You can see it in second 9 of the example (https://javdome.github.io/vimeo-interactive/)

I do not have clear what exactly you want... please, can you give me an extended explanation??

**Comment by javdome** [comment]
Now is available the "Modal with choosing options":
![Modal](https://user-images.githubusercontent.com/36993404/80379106-ef0bea80-889d-11ea-9f9e-438ac2142148.jpg)

I do not have clear what exactly you want... Can you explain

**Comment by christianck02031995** [comment]
Suppose i have a video and  i hosted the video to vimeo.
then i need to add some interactivities to the video.
and all over the world need to access the video with that interactivities.
I going to implement this using php and angular.

**Comment by javdome** [comment]
I think that if you need something more complex, and you are going to start developing an application, I suppose the best option is to use the official vimeo library to control the player:
https://github.com/vimeo/player.js/
And build your application specifically for your needs.

**Comment by christianck02031995** [comment]
i want video to play in vimeo without any player implementation.
after uploading the video i got the video id
then is it possible to add interactivities to the video with the help of frond end tech.
added interactivity data will keep in our db.
is this method possible ?

**Comment by javdome** [comment]
I don't really know... just try it

**Comment by christianck02031995** [comment]
ok

**Comment by christianck02031995** [comment]
Hi
In your code the file app.js contains a lengthy code.
That complete code is for the implementation of interactivity tools?

**Comment by javdome** [comment]
The app.js launch the interactivities defined in the config.js file

**Comment by christianck02031995** [comment]
Is there any api reference to manage the play/pause in vimeo video?

**Comment by javdome** [comment]
Yes... my repo uses the official vimeo API player:
https://github.com/vimeo/player.js/

There you can find plenty of methods and event for vimeo videos.
